import Head from "next/head";
import Footer from "./footer";
import Header from "./header";

export default function Base(props) {
  return (
    <>
      <Head>
        {props.title ? (
          <title>{props.title} - Huei Select</title>
        ) : (
          <title>Huei Select</title>
        )}
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <div id="main-content">{props.children}</div>
      <Footer></Footer>
    </>
  );
}
